endwin =>     endwin();
initscr =>     stdscr = initscr();
keypad =>         keypad(statusbar, TRUE);/* enable keyboard mapping */
nonl =>         nonl();                 /* tell curses not to do NL->CR/NL on output */
cbreak =>         cbreak();               /* take input chars one at a time, no wait for \n */
echo =>         noecho();               /* dont echo input */
curs_set =>         curs_set(0);            /* set cursor invisible */
timeout =>         wtimeout(statusbar, cfg.nc_timeout);/* timeout getch */
keypad =>         keypad(statusbar, TRUE);/* enable keyboard mapping */
nonl =>         nonl();                 /* tell curses not to do NL->CR/NL on output */
cbreak =>         cbreak();               /* take input chars one at a time, no wait for \n */
echo =>         noecho();               /* dont echo input */
curs_set =>         curs_set(0);            /* set cursor invisible */
timeout =>         wtimeout(statusbar, -1);/* no timeout on getch */
curs_set =>         curs_set(1);            /* set cursor visible */
cbreak =>         nocbreak();             /* wait for \n */
echo =>         echo();                 /* echo input */
timeout =>         wtimeout(statusbar, -1);/* no timeout on getch */
timeout =>         wtimeout(stdscr, 1000);
