newterm => 		out_screen = newterm(getenv("TERM"), stdout, tty);
set_term => 		set_term(out_screen);
initscr => 		initscr();
cbreak => 	cbreak();
echo => 	noecho();
nodelay => 	nodelay(stdscr, TRUE);
nonl => 	nonl();
intrflush => 	intrflush(stdscr, FALSE);
keypad => 	keypad(stdscr, TRUE);
endwin => 	endwin();
