init_pair =>     init_pair(index, back, fore);
initscr =>   initscr();
has_colors => 	if(!has_colors()) {
endwin =>     endwin();
start_color =>   start_color();
cbreak =>   cbreak();
keypad =>   keypad(stdscr, TRUE);
echo =>   noecho();
curs_set =>   curs_set(0);
endwin =>   endwin();
